config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root :to => 'users#index'
      resources :users, only: [:index, :show] do
        resources :posts do
        resources :comments, only: [:new, :create]
        resources :comments, only: [:new, :create, :destroy]
        resources :likes, only: [:new, :create]
        end
      end
      get "api/users/:author_id/posts", to: "api/posts#index"
      get "api/users/:author_id/posts/:id", to: "api/comments#index"
      post "api/users/:author_id/posts/:id/comments/new", to: "api/comments#create"
    
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

     can :read, :all
     can :create, [Post, Comment]

     if user.role = 'admin'
      can :manage, :all
     else
      can :destroy, Post, author_id: user.id
      can :destroy, Comment, author_id: user.id
     end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_like_counter

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments, dependent: :destroy

  has_many :most_recent_comments, -> { order(created_at: :desc).limit(5) }, class_name: 'Comment'

  after_save :post_counter_update

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def post_counter_update
    author.increment!(:posts_counter)
  end

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :user_id
  has_many :comments, foreign_key: :user_id

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def index
      user = User.find(params[:author_id])
      post = user.posts.find(params[:id])
      comments = post.comments
  
      render json: comments
    end
  
    def create
      post = Post.find(params[:post_id])
      comment = post.comments.build(comment_params)
      comment.user = current_user
  
      if comment.save
        render json: comment, status: :created
      else
        render json: { errors: comment.errors.full_messages }, status: :unprocessable_entity
      end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:text)
    end
  end

app/controllers/api/posts_controller.rb
class Api::PostsController <ApplicationController
    def index
     user = User.find(params[:author_id])
      posts = user.posts
  
      if posts.present?
        render json: { message: 'Posts loaded successfully', data: posts }, status: :ok
      else
        render json: { message: 'Opps! might be missing something' }, status: :unprocessable_entity
      end
    end
  
  end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
    def index
        @users = User.all
        render json: @users
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :update_allowed_arameters, if: :devise_controller?

  protected

  def update_allowed_arameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def sign_out_current_user
    cookies.delete(:_session_id)
  end
end

app/controllers/comments_controller.rb
    class CommentsController < ApplicationController
    def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(post_params)
    if @comment.save
      redirect_to user_post_path(@post.author_id, @post.id)
    else
      redirect_to user_post_comment_path(@post.author_id, @post.id)
    end
  end

    def destroy
    @comment = Comment.find(params[:id])
    @comment.post.comments_counter -= 1
    @comment.post.save
    @comment.destroy
    redirect_to user_posts_path(@comment.user.id)
    end

  private

      def post_params
      params.require(:comment).permit(:text, :post_id, :user_id)
      end
    end

app/controllers/likes_controller.rb
# Purpose: Controller for likes
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(like_params)
    @like.save
    redirect_to user_post_path(@post.author_id, @post.id)
  end

  private

  def like_params
    params.require(:like).permit(:user_id, :post_id)
  end
end

app/controllers/posts_controller.rb
    class PostsController < ApplicationController
      before_action :set_current_user, only: %i[new create show]
      before_action :authenticate_user!
      load_and_authorize_resource

      before_action :set_user

      def index
      @user = User.find_by_id(params[:user_id]) # params[:user_id] is the id of the user
      @posts = Post.where(author_id: params[:user_id]).includes(:most_recent_comments)
      end

      def show
      @current_user = current_user
      @post = Post.find_by_id(params[:id])
    end

    def new
    @user = current_user # params[:user_id] is the id of the user
    @post = Post.new
    end

    def create
    # user = current_user
    @post = Post.new(post_params)
    return unless @post.save

    redirect_to user_post_path(current_user.id, @post.id)
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @post.destroy
    @user.posts_counter -= 1
    @user.save
    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:author_id, :title, :text)
  end

  def set_current_user
    @current_user = current_user
  end

      def set_user
      @user = User.find(params[:user_id])
      end
    end

app/controllers/users_controller.rb
    class UsersController < ApplicationController
    def index
    @users = User.all
    @current_user = current_user
    end

    def show
    @user = User.find_by_id(params[:id])
    @posts = @user.most_recent_posts
    @posts = Post.where(author_id: @user.id)
   end

  # def new
  #  @user = User.new
  # end

  # def create
  #  @user = User.create(params[:user])
  #  if @user.save
  #    redirect_to user_path(@user.id)
  #  else
  #    render :new
  #  end
  # end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Posts from user 1</title>
</head>
<body>
  <div id="user_info">
    <div id="user_image">
      <% if @user.photo %>
        <img src=<%= @user.photo %> alt="User Photo">
      <% else %>
        <img src="no_pic.png" alt="User Photo">
      <% end %>
    </div>
    <div id="user_name_and_posts">
      <h1><%= @user.name %></h1>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div id="user_posts">
    <% @posts.each do |post| %>
      <a href=<%= user_post_path(post.author_id, post.id) %>>
      <div class="user_post">
        <div class="post">
          <h3><%= post.title %></h3>
          <p maxlength="150"><%= post.text %></p>
          <span>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
        </div>
        <div class="comments">
          <% if post.comments.length>=1 %>
          <% post.comments.each do |comment| %>
            <div class="comment">
              <p><%= comment.user.name %>: <%= comment.text %></p>
            </div>
          <% end %>
          <% else %>
            <p class="nocomments">No comments yet</p>
          <% end %>
        </div>
      </div>
      </a>
    <% end %>
  </div>
    <button>Pagination</button>
</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Post</title>
</head>
<body>
  <p>Current user: <%= @user.name %> </p>
  <h1>Create New Post</h1>
  <div class="container">
    <%= form_with(model: @post, url: user_posts_path, method: :post) do |form| %>
      <div class="form-container">
        <div class="flex form-title">
          <%= form.label :title, 'Title: ' %>
          <%= form.text_field :title %>
        </div>
        <%= form.text_area :text, placeholder: "Enter content of the article here" %>
        <%= form.hidden_field :author_id, value: @user.id %>
        
        <%= form.submit 'Create Post' %>
      </div>
    <% end %>
  </div>
  
</body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Post <%= params[:id] %> from User <%= params[:user_id] %></title>
</head>
<body>
  <div class="user_post">
  <div class="post">
    <h3><%= @post.title %> by <%= @post.author.name %></h3>
    <span>Likes: <%= @post.likes_counter %>, Comments: <%= @post.comments_counter %></span>
    
    <!-- likes button form -->
    <%= form_with model: Like, url: user_post_likes_path(@post.author_id, @post.id ), method: :post do |form| %>
      <%= form.hidden_field :user_id, value: @current_user.id %>
      <%= form.hidden_field :post_id, value: @post.id %>
      <%= form.submit "Like" %>
    <% end %>
    <p><%= @post.text %></p>

  <% if can?(:destroy, @post) %>
  <%=  button_to 'Delete Post', user_post_path(@user, @post), method: :delete%>
  <% end %>
  </div>
  <div class="comments">
    <% if @post.comments.length>=1 %>
      <% @post.comments.each do |comment| %>
        <div class="comment">
          <p><%= comment.user.name %>: <%= comment.text %></p>
                  <% if can?(:destroy, comment) %>
          <%= button_to 'Delete', user_post_comment_path(comment.post.author, comment.post, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' }, class: 'btn btn-danger' %>
        <% end %>    

        </div>
      <% end %>
      <p class="nocomments">No comments yet</p>
    <% end %>
  </div>
  <!-- form for a new comment -->
  <div class="new_comment">
    <%= form_with(model: Comment, url: user_post_comments_path(@post.author_id, @post.id ), method: :post, local: true) do |form| %>
      <span><%= @current_user.name %>: </span>
      <%= form.text_field :text, placeholder: "Enter your comment here" %>
      <%= form.hidden_field :user_id, value: @current_user.id %>
      <%= form.hidden_field :post_id, value: @post.id %>
      <%= form.submit 'Add Comment' %>
    <% end %>
  </div>

  </div>
</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>users</title>
  <%= stylesheet_link_tag "styles" %>
</head>
<body>
  <h1>Users list</h1>
  <a href=<%= "/users/#{@current_user.id}/posts/new"%> >
    <button>New Post</button>
    </a>
  <div class="container">
    <%@users.each do |user|%>
      <a href=<%= user_path(user.id)%>>
      <div class="user">
        <div class="user_image">
        <% if user.photo %>
          <img src=<%= user.photo %> alt="Profile picture">
        <% else %>
          <img src="no_pic.png" alt="Profile picture">
        <% end %>
        </div>
        <div class="user user-info">
          <h2><%= user.name %></h2>
          <p>Number of posts: <%= user.posts_counter %></p>
        </div>
      </div>
      </a>
    <%end%>
  </div>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User <%= params[:id] %></title>
  <%= stylesheet_link_tag "styles" %>
</head>
<body>
  <div class="container">
  <div id="user_info">
    <div class="user_image">
      <% if @user.photo %>
        <img src=<%= @user.photo %> alt="User Photo">
      <% else %>
        <img src="no_pic.png" alt="User Photo">
      <% end %>
    </div>
    <div id="user_name_and_posts">
      <h1><%= @user.name %></h1>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div id="bio">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>
  <div id="posts">
    <% @posts.each do |post| %>
    <a href=<%= user_post_path(@user.id, post.id) %>>
      <div class="post">
        <h3><%= post.title %></h3>
        <p class="cropped-text"><%= post.text %></p>
        <span>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
      </div>
    </a>
    <% end %>
  </div>
  <a href=<%= user_posts_path(@user.id) %>>
    <button>See all posts</button>
  </a>
  </div>
</body>
</html>